/* Edit this file to personalise the florist-facing demo hub. */
window.DEMO_CONFIG = {
  brandName: "Ming AI Automations",
  partnerName: "Paws & Co.",
  defaultLanguage: "zh",
  instagramUrl: "#",
  previewBasePath: "experience/index.html",
  content: {
    zh: {
      privateDemo: "花礼加购体验 · 专属预览",
      navExperiences: "体验款式",
      navFlow: "合作流程",
      navQr: "QR 花卡",
      heroEyebrow: "PET MEMORY × DIGITAL SURPRISE",
      heroTitle: "让一份对毛孩的爱，变成可以再次走进的回忆。",
      heroBody: "扫描 QR Code，宠物主人会进入一个由照片、音乐、留言与互动组成的私人纪念体验。",
      explore: "选择体验款式",
      viewFlow: "查看合作流程",
      mockPrivate: "仅为特别的人准备",
      mockScan: "扫描花卡，打开惊喜",
      mockThree: "三种专属体验",
      sectionEyebrow: "CHOOSE A PREVIEW",
      sectionTitle: "为每一段毛孩故事，准备三种温柔的打开方式。",
      sectionBody: "每一个示范都会打开完整的手机体验。无需输入密码，方便预览；正式客户版本仍可设置四位数密码。",
      loveTitle: "欢迎回家",
      loveBody: "纪念第一天、第一张照片和它成为家人后的每个小日常。",
      birthdayTitle: "毛孩生日",
      birthdayBody: "一个生日愿望、照片回忆、音乐与来自最爱的人的声音。",
      dateTitle: "温柔纪念",
      dateBody: "一封写给毛孩的信，把它留下的温暖瞬间好好收藏。",
      preview: "开始体验",
      previewNote: "建议使用手机打开并开启声音",
      diyEyebrow: "MAKE IT YOURS",
      diyTitle: "先把这个示范变成属于你的惊喜。",
      diyBody: "资料只用于这次浏览器预览，不会上传给我们。正式订单仍由我们代为制作。",
      recipientLabel: "收礼人的名字",
      recipientPlaceholder: "例如：Celeste",
      senderLabel: "你的名字",
      senderPlaceholder: "例如：Ming",
      languageLabel: "惊喜显示语言",
      endingLabel: "最后亲手写出的那句话（可选）",
      endingPlaceholder: "例如：我爱你，一直都是。",
      aiTitle: "不知道怎么写给它？让我帮你开始。",
      aiBadge: "私密草稿",
      aiBody: "写下几个关键词，选择语气，即可获得三段可编辑的灵感。内容只在这次浏览器预览中使用。",
      aiToneLabel: "想要的感觉",
      aiToneWarm: "温柔真诚",
      aiTonePlayful: "轻松甜蜜",
      aiTonePoetic: "浪漫诗意",
      aiOccasionLabel: "这份惊喜是为了",
      aiOccasionPlaceholder: "例如：我们的两周年",
      aiMemoryLabel: "告诉我一点你们的故事",
      aiMemoryPlaceholder: "例如：第一次一起看电影、她总会记得我爱喝的咖啡。",
      aiButton: "生成三段写作灵感",
      aiIdeaShort: "开场短句",
      aiIdeaMemory: "回忆段落",
      aiIdeaFinal: "结尾一句",
      aiUse: "用在最后一句 →",
      aiDefaultOccasion: "今天",
      aiDefaultMemory: "我们一起经历的小事",
      voiceLabel: "录一段私人语音（可选）",
      voicePrivacy: "允许麦克风后即可录音。录音只保存在这个设备，不会上传。",
      recordStart: "开始录音",
      recordStop: "停止录音",
      recordReady: "录音完成，可以先试听。",
      recordClear: "删除",
      recordError: "无法使用麦克风。请检查浏览器权限，或直接继续无语音的示范。",
      diySkip: "直接查看示范",
      diyLaunch: "打开我的专属预览",
      flowEyebrow: "SIMPLE PARTNER FLOW",
      flowTitle: "Celeste 继续掌握客户关系，我们负责制作。",
      flowBody: "顾客仍然向 Celeste 下单和付款。Celeste 只需要把资料转发给 Ming AI Automations。",
      step1Title: "顾客选择加购",
      step1Body: "Celeste 在花礼订单中询问顾客，是否要加购 Premium QR 祝福体验。",
      step2Title: "WhatsApp 收集资料",
      step2Body: "顾客把名字、照片、文字、音乐或语音交给 Celeste，再由 Celeste 转发给我们。",
      step3Title: "收到 QR 花卡",
      step3Body: "我们完成网页并交付 QR。Celeste 可打印在手写卡上，或直接把电子花卡发给顾客。",
      qrEyebrow: "FROM FLOWERS TO A MOMENT",
      qrTitle: "一张小小的 QR 花卡，把实体礼物延伸成完整体验。",
      qrBody: "QR Code 可以印在 Celeste 原本的手写卡上，不改变现有送花流程。若暂时没有打印设备，也可以发送电子版本。",
      qrCardLabel: "一份只属于你的礼物",
      qrCardTitle: "我为你准备了一份小惊喜。",
      qrCardScan: "扫描后再慢慢打开",
      viewQr: "查看可打印 QR 花卡 →",
      feature1: "中英马三语",
      feature2: "手机优先设计",
      feature3: "照片、音乐与语音",
      feature4: "密码与私人链接",
      feature5: "可打印 QR 花卡",
      closingEyebrow: "FOR CELESTE FLORIST",
      closingTitle: "把祝福，从卡片上的一句话，变成一段会被记住的体验。",
      closingBody: "这不是取代 Celeste 的手写卡，而是为愿意加购的顾客提供一个更有情绪价值的选择。",
      reopen: "再次选择体验",
      instagram: "查看合作伙伴"
    },
    en: {
      privateDemo: "Floral add-on experience · Private preview",
      navExperiences: "Experiences",
      navFlow: "Partner flow",
      navQr: "QR flower card",
      heroEyebrow: "PET MEMORY × DIGITAL SURPRISE",
      heroTitle: "Turn the love for a pet into a memory you can step back into.",
      heroBody: "A QR code opens a private pet-parent experience made from photos, music, messages and gentle interaction.",
      explore: "Choose an experience",
      viewFlow: "See the partner flow",
      mockPrivate: "Made for someone special",
      mockScan: "Scan the card to begin",
      mockThree: "Three private experiences",
      sectionEyebrow: "CHOOSE A PREVIEW",
      sectionTitle: "Three gentle ways to honour a pet’s story.",
      sectionBody: "Each preview opens the complete mobile journey. Demo mode skips the passcode for convenience; client versions can retain the four-digit lock.",
      loveTitle: "Welcome Home",
      loveBody: "The first day, the small habits, and every moment a pet becomes family.",
      birthdayTitle: "Pet Birthday",
      birthdayBody: "A birthday wish, favourite photos, music and a personal voice message.",
      dateTitle: "In Loving Memory",
      dateBody: "A quiet letter, a memory film, and a gentle place to keep a pet close.",
      preview: "Start preview",
      previewNote: "Best experienced on a phone with sound enabled",
      diyEyebrow: "MAKE IT YOURS",
      diyTitle: "Make this preview feel like your own surprise.",
      diyBody: "These details are used only for this browser preview and are not uploaded to us. We still prepare the final customer order for you.",
      recipientLabel: "Recipient’s name",
      recipientPlaceholder: "For example: Celeste",
      senderLabel: "Your name",
      senderPlaceholder: "For example: Ming",
      languageLabel: "Experience language",
      endingLabel: "Final handwritten line (optional)",
      endingPlaceholder: "For example: I love you. Always have.",
      aiTitle: "Not sure how to write to them? Start here.",
      aiBadge: "Private draft",
      aiBody: "Share a few details and choose a feeling. You will receive three editable ideas, used only in this browser preview.",
      aiToneLabel: "Choose a feeling",
      aiToneWarm: "Warm & sincere",
      aiTonePlayful: "Playful & sweet",
      aiTonePoetic: "Romantic & poetic",
      aiOccasionLabel: "This surprise is for",
      aiOccasionPlaceholder: "For example: our second anniversary",
      aiMemoryLabel: "Share one small memory",
      aiMemoryPlaceholder: "For example: our first movie, and how she remembers my coffee order.",
      aiButton: "Create three writing ideas",
      aiIdeaShort: "Opening line",
      aiIdeaMemory: "Memory paragraph",
      aiIdeaFinal: "Final line",
      aiUse: "Use as final line →",
      aiDefaultOccasion: "today",
      aiDefaultMemory: "the small things we have shared",
      voiceLabel: "Record a private voice message (optional)",
      voicePrivacy: "Grant microphone access to record. Audio stays on this device and is not uploaded.",
      recordStart: "Start recording",
      recordStop: "Stop recording",
      recordReady: "Recording ready. You can listen before continuing.",
      recordClear: "Delete",
      recordError: "The microphone was unavailable. Check browser permission or continue without a voice message.",
      diySkip: "View without personalising",
      diyLaunch: "Open my personalised preview",
      flowEyebrow: "SIMPLE PARTNER FLOW",
      flowTitle: "Celeste keeps the customer relationship. We handle production.",
      flowBody: "Customers continue ordering and paying Celeste. Celeste only forwards the required details to Ming AI Automations.",
      step1Title: "Customer selects the add-on",
      step1Body: "Celeste asks whether the customer wants to add a Premium QR Greeting Experience to the flower order.",
      step2Title: "Details through WhatsApp",
      step2Body: "The customer sends names, photos, text, music or voice to Celeste, who forwards the order to us.",
      step3Title: "Receive the QR card",
      step3Body: "We complete the website and deliver the QR. Celeste can print it on the handwritten card or send the digital card.",
      qrEyebrow: "FROM FLOWERS TO A MOMENT",
      qrTitle: "One small QR flower card extends a physical gift into a complete experience.",
      qrBody: "The QR can be printed on Celeste’s existing handwritten card without changing the delivery flow. A digital version works when printing is unavailable.",
      qrCardLabel: "A private gift, just for you",
      qrCardTitle: "I prepared a little surprise for you.",
      qrCardScan: "Scan and open it slowly",
      viewQr: "View the printable QR card →",
      feature1: "EN, BM & Chinese",
      feature2: "Mobile-first design",
      feature3: "Photos, music & voice",
      feature4: "Passcode & private link",
      feature5: "Printable QR flower card",
      closingEyebrow: "FOR CELESTE FLORIST",
      closingTitle: "Turn one line on a greeting card into an experience they remember.",
      closingBody: "It does not replace Celeste’s handwritten card. It gives customers who want an upgrade a more emotionally valuable option.",
      reopen: "Choose another preview",
      instagram: "View partner"
    }
  }
};
